stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/initial_raw # Raw data

  process_data:
    cmd: python src/preprocess_data.py
    deps:
    - src/preprocess_data.py
    - data/initial_raw # Raw data
    outs:
    - data/processed/ # Processed data
    - models/c1_BoW_Sentiment_Model.pkl # CountVectorizer

  train_model:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - data/processed/ # Processed data
    outs:
    - models/Classifier_Sentiment_Model.joblib # Classifier
  
  eval_model:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/processed/ # Processed data
    - models/c1_BoW_Sentiment_Model.pkl # CountVectorizer
    - models/Classifier_Sentiment_Model.joblib # Classifier
    metrics:
      - data/model_eval/metrics.json
