stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/a1_RestaurantReviews_HistoricDump.tsv

#  process_data: TODO: SEPARATE THE PREPROCESSING FROM TRAIN DATA?
#    cmd: python src/preprocess_data.py
#    deps:
#    - src/preprocess_data.py
#    outs:
#    - outputs/preprocessed_data.joblib
  train_model:
    cmd: python src/train_model.py
    deps:
    - data/a1_RestaurantReviews_HistoricDump.tsv
    - src/train_model.py
    outs:
    - model/Classifier_Sentiment_Model.joblib
  #TODO: EVAL
