stages:
  get_data:
    cmd: python src/get_data.py
    deps:
    - src/get_data.py
    outs:
    - data/initial_raw

  process_data:
    cmd: python src/preprocess_data.py
    deps:
    - src/preprocess_data.py
    - data/initial_raw
    outs:
    - data/processed/

  train_model:
    cmd: python src/train_model.py
    deps:
    - src/train_model.py
    - data/processed/
    outs:
    - models/Classifier_Sentiment_Model.joblib
  
  eval_model:
    cmd: python src/evaluate.py
    deps:
    - src/evaluate.py
    - data/processed/
    - models/Classifier_Sentiment_Model.joblib
