stages:
  get_data:
    cmd: python3 -m src.get_data
    deps:
    - src/get_data.py
    outs:
    - data/initial_raw # Raw data

  process_data:
    cmd: python3 -m src.preprocess_data
    deps:
    - src/preprocess_data.py
    - data/initial_raw # Raw data
    outs:
    - data/processed/ # Processed data
    - models/c1_BoW_Sentiment_Model.pkl # CountVectorizer

  train_model:
    cmd: python3 -m src.train_model
    deps:
    - src/train_model.py
    - data/processed/ # Processed data
    params:
    - model.is_alternative_model # Type of classifier that is trained is dependent on this parameter
    outs:
    - models/Classifier_Sentiment_Model.joblib # Classifier
  
  eval_model:
    cmd: python3 -m src.evaluate
    deps:
    - src/evaluate.py
    - data/processed/ # Processed data
    - models/c1_BoW_Sentiment_Model.pkl # CountVectorizer
    - models/Classifier_Sentiment_Model.joblib # Classifier
    metrics:
      - metrics.json
