name: Lint Check Code

on:
  push:
    branches: ["*"]
  pull_request:
    branches: [main]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install pylint==3.3.6

      - name: Run pylint and extract score
        id: pylint_score
        run: |
          SCORE=$(pylint src/ | tee pylint.log | tail -2 | head -1 | grep -oP '\d+\.\d+')
          echo "score=$SCORE" >> $GITHUB_OUTPUT

      - name: Update README with pylint score
        run: |
          sed -i "s/Pylint Score: <!-- PYLINT_SCORE -->.*/Pylint Score: <!-- PYLINT_SCORE --> ${SCORE}\/10/" README.md
        env:
          SCORE: ${{ steps.pylint_score.outputs.score }}

