name: pylint
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Installing dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Analyzing the code with pylint
      run: |
          SCORE_GETDATA=$(pylint src/get_data.py | grep 'Your code has been rated at ' | awk '{print $7}' | sed 's/...$//')
          echo "Pylint score for get_data.py: $SCORE_GETDATA"
          echo "PYLINT_SCORE_GETDATA=$SCORE_GETDATA" >> $GITHUB_ENV