name: Release model-training

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  build-and-release-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # DVC steps for local storage
      - name: Initialize DVC if needed
        run: |
          if [ ! -d ".dvc" ]; then
            dvc init
          fi

      - name: Set up local DVC remote
        run: |
          mkdir -p ~/remotedvc
          dvc remote add -f -d mylocalremote ~/remotedvc
          dvc remote default mylocalremote

      - name: Reproduce pipeline (train model)
        run: dvc repro
        
      - name: Upload trained model to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            models/Classifier_Sentiment_Model.joblib
            models/c1_BoW_Sentiment_Model.pkl
