name: Release model-training

on: [push]
  #push: 
    # tags:
    #   - "v[0-9]+.[0-9]+.[0-9]+*"

permissions:
  contents: write

jobs:
  build-and-release-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Generate GDrive credentials.json from GitHub Secret
        env:
          GDRIVE_CREDENTIALS_DATA: ${{ secrets.GDRIVE_CREDENTIALS_DATA_BASE64 }}
        run: |
          echo $GDRIVE_CREDENTIALS_DATA | base64 -d > credentials.json

      - name: Initialize DVC if needed
        run: |
          if [ ! -d ".dvc" ]; then
            dvc init
          fi

      - name: Set up DVC Remote
        run: |
            dvc remote add myremote gdrive://${{ secrets.GDRIVE_FOLDER_ID }} -f 
            dvc remote default myremote
            dvc remote modify myremote gdrive_acknowledge_abuse true -f
            dvc remote modify myremote gdrive_use_service_account true -f
            dvc remote modify myremote --local \
            gdrive_service_account_json_file_path credentials.json -f

      - name: DVC - Pull models and data
        run: dvc pull

      - name: DVC - Reproduce pipeline
        run: dvc repro


      # - name: Upload trained model to GitHub Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     files: |
      #       models/Classifier_Sentiment_Model.joblib
      #       models/c1_BoW_Sentiment_Model.pkl
